### ISSUE TITLE
Assertion failed error

### ISSUE THREAD

**Issue by wootsy12** [patrikhuber/eos-model-viewer#13]
Hi,

I compiled the model viewer fine and managed to run it, however, after trying to import the wrong filetype for the blendshape, the program crashed, and now it keeps giving me the following error:

`Assertion failed: (internal::UIntPtr(array) & (15)) == 0 && "this assertion is explained here: " "http://eigen.tuxfamily.org/dox-devel/group__TopicUnalignedArrayAssert.html" " **** READ THIS WEB PAGE !!! ****", file d:\documents\code\eos\eos-model-viewer\external\eos\3rdparty\eigen\eigen\src\core\densestorage.h, line 109`

I read the webpage but it doesn't seem clear in this case which of those causes would be triggering it. I tried rebuilding but the error persists. Any idea what might be causing this?

**Comment by wootsy12** [comment]
I got this to work by rebuilding the entire thing. No idea what caused it to corrupt along the way but a rebuild fixed it.

**Comment by patrikhuber** [comment]
Hi,

Great that you got it to work. Perhaps you did a 32-bit build first, and then a 64-bit build. Those Eigen alignment issues shouldn't normally happen when compiled in 64-bit mode, because all modern compilers usually do "the right thing" in terms of alignment in that scenario - or at least I've heard/read, if I remember correctly. I'd always recommend building for the x64 target.
